# Generated by Django 3.1.6 on 2021-02-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
            ],
        ),
    ]
