# Generated by Django 3.1.6 on 2021-02-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0004_team_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestart',
            name='event_duration',
            field=models.IntegerField(default=15),
        ),
    ]
